apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: photographer-backend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"               # Max 1 instance            # Min 0 (scale to 0)
        run.googleapis.com/cpu: "8"                         # 8 CPUs
        run.googleapis.com/memory: "32Gi"                   # 64 GiB RAM
        run.googleapis.com/execution-environment: gen2      # Use Gen2 if available
    spec:
      containers:
        - image: gcr.io/photographerbackend/photographer-backend
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_SECRET_KEY
              value: "6d48a0a387f89201a0258d6f32b076d1dc59fd12f4575b70"
            - name: MONGO_URI
              value: "mongodb+srv://communityhopeai:cI2VBpLXy1V2lR5m@cluster0.8lvdj5s.mongodb.net/users?retryWrites=true&w=majority&appName=Cluster0"
            - name: JWT_SECRET_KEY
              value: "92fba970afec18552f3f8c42d835995d880f3c4b12f17027"
            - name: FIREBASE_CREDENTIALS
              value: "config/firebase-adminsdk.json"
            - name: FRONTEND_URL
              value: "https://photograperfaceai.netlify.app"
            - name: BACKEND_URL
              value: "https://photographer-backend-985262164867.asia-south1.run.app"
            - name: GCS_BUCKET
              value: "qr-code-image-gcp"
